# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy to Google Play"
  lane :beta do
    gradle(
      task: "clean assembleRelease",  # Ensure you are building a release version
      build_type: "Release"
    )

    upload_to_play_store(
      track: "internal",  # You can choose `alpha`, `beta`, or `production` track
      json_key: "fastlane/play-store-key.json",  # Path to the service account JSON file
      package_name: "com.example.CICDdemo"  # Ensure the package name is correct
    )
  end
end
