# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy to Google Play"
  lane :beta do
    gradle(
      task: "bundleRelease"  # Use bundleRelease to generate the AAB file
    )

    upload_to_play_store(
      track: "internal",  # or alpha/beta/production
      aab: "app/build/outputs/bundle/release/app-release.aab",  # Path to your AAB file
      json_key: "fastlane/play-store-key.json",
      package_name: "com.kah.CICDdemo",
      changes_not_sent_for_review: true  # Keeps release in draft until manually published
    )
  end
end



